# Generated by Django 3.1.6 on 2021-09-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_pub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum: 255 caractères', max_length=255, verbose_name='Poste')),
                ('name', models.CharField(help_text='Maximum: 255 caractères', max_length=255, verbose_name='Nom et prénom')),
                ('description', models.TextField(null=True, verbose_name='Mots clés')),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.TextField(null=True, verbose_name='Mots clés'),
        ),
    ]
