# Generated by Django 3.1.6 on 2021-09-19 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210919_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, help_text='Maximum: 255 caractères', max_length=255, verbose_name='Titre'),
            preserve_default=False,
        ),
    ]
