# Generated by Django 3.1.6 on 2021-09-12 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Mots clés'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
