# Generated by Django 3.2.7 on 2021-09-09 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210908_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, help_text='Maximum: 255 caractères', max_length=255, verbose_name='Auteur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Maximum: 255 caractères', max_length=255, verbose_name='Titre'),
        ),
    ]
